In [1]:
import pandas as pd

In [2]:
movie=pd.read_csv('dataset.csv')

In [3]:
movie

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [4]:
movie.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [5]:
movie=movie[['id','title','genre']]

In [6]:
movie

,id,title,genre
0,278,The Shawshank Redemption,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance"
2,238,The Godfather,"Drama,Crime"
3,424,Schindler's List,"Drama,History,War"
4,240,The Godfather: Part II,"Drama,Crime"
...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,"Thriller,Action,Crime"

In [7]:
new_list=movie

In [8]:
new_list

,id,title,genre
0,278,The Shawshank Redemption,"Drama,Crime"
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance"
2,238,The Godfather,"Drama,Crime"
3,424,Schindler's List,"Drama,History,War"
4,240,The Godfather: Part II,"Drama,Crime"
...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy"
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure"
9997,13995,Captain America,"Action,Science Fiction,War"
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama"
9999,455957,Domino,"Thriller,Action,Crime"

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
counter=CountVectorizer(max_features=10000,stop_words='english')

In [11]:
counter

CountVectorizer(max_features=10000, stop_words='english')

In [12]:
vector=counter.fit_transform(new_list['genre'].values.astype('U')).toarray()

In [13]:
vector.shape

(10000, 21)

In [14]:
import ast
movie['genre'] = movie['genre'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

ValueError: malformed node or string on line 1: <ast.Name object at 0x000001B76E0FEC10>

In [17]:
import ast

def safe_parse_genre(x):
    if isinstance(x, list):
        return x
    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)
            return parsed if isinstance(parsed, list) else [parsed]
        except (ValueError, SyntaxError):
            return [g.strip() for g in x.split(',')]
    return []

movie['genre'] = movie['genre'].apply(safe_parse_genre)

C:\Users\JAGADEESH\AppData\Local\Temp\ipykernel_5740\3241519122.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie['genre'] = movie['genre'].apply(safe_parse_genre)

In [23]:
import ast

def safe_parse_genre(x):
    if isinstance(x, list):
        return x
    if isinstance(x, str):
        try:
            parsed = ast.literal_eval(x)
            return parsed if isinstance(parsed, list) else [parsed]
        except (ValueError, SyntaxError):
            return [g.strip() for g in x.split(',')]
    return []

# Safely create a modifiable copy of the DataFrame before applying changes
movie = movie.copy()
movie['genres'] = movie['genre'].apply(safe_parse_genre)

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity=cosine_similarity(vector)

In [26]:
similarity

array([[1.        , 0.40824829, 1.        , ..., 0.        , 0.35355339,
        0.40824829],
       [0.40824829, 1.        , 0.40824829, ..., 0.        , 0.28867513,
        0.        ],
       [1.        , 0.40824829, 1.        , ..., 0.        , 0.35355339,
        0.40824829],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.25      ,
        0.28867513],
       [0.35355339, 0.28867513, 0.35355339, ..., 0.25      , 1.        ,
        0.28867513],
       [0.40824829, 0.        , 0.40824829, ..., 0.28867513, 0.28867513,
        1.        ]])

In [27]:
new_list[new_list['title']=="The Godfather"].index[0]

np.int64(2)

In [28]:
distance= sorted(list(enumerate(similarity[2])),reverse=True,key=lambda vector:vector[1])
for i in distance[0:5]:
    print(new_list.iloc[i[0]].title)

The Shawshank Redemption
The Godfather
The Godfather: Part II
GoodFellas
Once Upon a Time in America

In [29]:
def recommand(movies):
    index=new_list[new_list['title']==movies].index[0]
    distance=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_list.iloc[i[0]].title)

In [30]:
recommand("Iron Man")

The Empire Strikes Back
Inception
Avengers: Endgame
Avengers: Infinity War
Everything Everywhere All at Once

In [31]:
import pickle

In [32]:
pickle.dump(new_list,open('movies_list.pkl','wb'))

In [33]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [34]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [35]:
pickle.load(open('movies_list.pkl','rb'))

,id,title,genre,genres
0,278,The Shawshank Redemption,"[Drama, Crime]","[Drama, Crime]"
1,19404,Dilwale Dulhania Le Jayenge,"[Comedy, Drama, Romance]","[Comedy, Drama, Romance]"
2,238,The Godfather,"[Drama, Crime]","[Drama, Crime]"
3,424,Schindler's List,"[Drama, History, War]","[Drama, History, War]"
4,240,The Godfather: Part II,"[Drama, Crime]","[Drama, Crime]"
...,...,...,...,...
9995,10196,The Last Airbender,"[Action, Adventure, Fantasy]","[Action, Adventure, Fantasy]"
9996,331446,Sharknado 3: Oh Hell No!,"[Action, TV Movie, Science Fiction, Comedy, Ad...","[Action, TV Movie, Science Fiction, Comedy, Ad..."
9997,13995,Captain America,"[Action, Science Fiction, War]","[Action, Science Fiction, War]"
9998,2312,In the Name of the King: A Dungeon Siege Tale,"[Adventure, Fantasy, Action, Drama]","[Adventure, Fantasy, Action, Drama]"
9999,455957,Domino,"[Thriller, Action, Crime]","[Thriller, Action, Crime]"

In [36]:
recommand("The Godfather")

The Shawshank Redemption
The Godfather
The Godfather: Part II
GoodFellas
Once Upon a Time in America